import sys
import json
import time
import math
from pathlib import Path
from ortools.constraint_solver import pywrapcp, routing_enums_pb2

# Proje kök dizinini ayarla
current_file = Path(__file__).resolve()
project_root = current_file.parents[2]
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))


class ORToolsTSPSolver:
    """
    Solves the Traveling Salesman Problem (TSP) using
    Google OR-Tools as a reference (benchmark) solver.
    """

    def __init__(self, distance_matrix):
        """
        Initializes the OR-Tools TSP solver.

        Parameters:
            distance_matrix (list[list[float]]): Distance matrix of the TSP
        """
        self.distance_matrix = distance_matrix
        self.num_cities = len(distance_matrix)

        # OR-Tools routing index manager
        self.manager = pywrapcp.RoutingIndexManager(
            self.num_cities,
            1,      # number of vehicles
            0       # depot (start city)
        )

        # Routing model
        self.routing = pywrapcp.RoutingModel(self.manager)

        self._register_distance_callback()
        self._set_search_parameters()

    def _register_distance_callback(self):
        """
        Registers the distance callback function for OR-Tools.
        """

        def distance_callback(from_index, to_index):
            # Returns the distance between the two nodes.
            from_node = self.manager.IndexToNode(from_index)
            to_node = self.manager.IndexToNode(to_index)
            
            # OR-Tools sadece INTEGER (Tam sayı) kabul eder.
            # Float değerleri yuvarlayarak (round) veriyoruz.
            # Hassasiyeti artırmak için normalde 100 ile çarpıp int yapılır ama
            # burada basitlik adına direkt yuvarlıyoruz.
            return int(round(self.distance_matrix[from_node][to_node]))

        transit_callback_index = self.routing.RegisterTransitCallback(
            distance_callback
        )

        self.routing.SetArcCostEvaluatorOfAllVehicles(
            transit_callback_index
        )

    def _set_search_parameters(self):
        """
        Sets the search parameters for OR-Tools.
        """
        self.search_parameters = pywrapcp.DefaultRoutingSearchParameters()
        self.search_parameters.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
        )

    def solve(self):
        """
        Solves the TSP using OR-Tools.

        Returns:
            dict: Best tour and its total cost
        """
        start_time = time.time()
        
        solution = self.routing.SolveWithParameters(
            self.search_parameters
        )

        end_time = time.time()
        duration = end_time - start_time

        if solution is None:
            # Çözüm bulunamazsa (nadiren olur)
            return None

        # Rotayı indexlerden nodlara çevir
        route = []
        index = self.routing.Start(0)
        
        while not self.routing.IsEnd(index):
            node = self.manager.IndexToNode(index)
            route.append(int(node)) # int dönüşümü JSON için önemli
            index = solution.Value(self.routing.NextVar(index))

        route.append(route[0])  # Başlangıç noktasına dön

        # OR-Tools maliyeti int hesapladı, biz gerçek float maliyeti tekrar hesaplayalım
        # Böylece Brute Force sonucuyla birebir kıyaslanabilir.
        real_cost = 0.0
        for i in range(len(route) - 1):
            u, v = route[i], route[i+1]
            real_cost += self.distance_matrix[u][v]

        return {
            "best_tour": route,
            "best_cost": real_cost,
            "duration": duration
        }


if __name__ == "__main__":
    """
    Main execution block:
    1. Loads TSP data from JSON (generated by tsp_generator).
    2. Solves using OR-Tools.
    3. Saves result to a separate JSON file.
    """

    print("Solving TSP using Google OR-Tools...")
    print("-" * 60)

    # Dosya yolları
    raw_data_dir = project_root / "data" / "raw"
    scenarios = [5, 6, 7]

    for n in scenarios:
        input_path = raw_data_dir / f"tsp_n{n}.json"
        output_path = raw_data_dir / f"tsp_n{n}_ortools_solution.json"

        if input_path.exists():
            print(f" [N={n}] Processing file: {input_path.name}")

            try:
                # 1. Veriyi Oku
                with open(input_path, 'r') as f:
                    data = json.load(f)
                
                # Matrisi al
                distance_matrix = data["distance_matrix"]

                # 2. Çöz
                solver = ORToolsTSPSolver(distance_matrix)
                result = solver.solve()

                if result:
                    # 3. Sonucu Kaydet
                    output_data = {
                        "Algorithm": "Google OR-Tools",
                        "Cities_N": n,
                        "Best_Path": result["best_tour"],
                        "Best_Cost": float(result["best_cost"]),
                        "Duration_Sec": result["duration"]
                    }

                    with open(output_path, 'w') as f:
                        json.dump(output_data, f, indent=4)

                    print(f"    -> Best Path: {result['best_tour']}")
                    print(f"    -> Cost: {result['best_cost']:.4f}")
                    print(f"    -> SAVED: {output_path.name}")
                else:
                    print("    -> ERROR: Solution could not be found.")
                
                print("")

            except Exception as e:
                print(f"    -> ERROR: {e}")
                import traceback; traceback.print_exc()

        else:
            print(f" [N={n}] WARNING: Input file not found ({input_path.name})")

    print("-" * 60)
    print("All tasks completed.")